language: python
python:
  - "3.6"
services:
  - mongodb
install:
  - pip install -r requirements.txt
jobs:
  include:
    - stage: unit test
      script:
      - python -m unittest discover

    - stage: build docker image - celery (base)
      if: branch != master
      script:
        - docker build -f Dockerfile -t $REPO_CELERY .
      after_success:
        - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
        - docker tag $REPO_CELERY $DOCKER_USER/$REPO_CELERY:$TRAVIS_BRANCH
        - docker push $DOCKER_USER/$REPO_CELERY:$TRAVIS_BRANCH

    - stage: build docker image - celery (latest)
      if: branch = master
      script:
        - docker build -f Dockerfile -t $REPO_CELERY .
      after_success:
        - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
        - docker tag $REPO_CELERY $DOCKER_USER/$REPO_CELERY:latest
        - docker push $DOCKER_USER/$REPO_CELERY:latest