language: python
python:
  - "3.6"
services:
  - mongodb
  - docker
jobs:
  include:
    - stage: build docker image - celery (latest)
      if: branch = master
      script:
        - docker build -f Dockerfile -t scheduler-maestro .
        - docker images
        - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
        - docker tag scheduler-maestro $DOCKER_USER/scheduler-maestro:latest
        - docker push $DOCKER_USER/scheduler-maestro:latest
